# Generated by CodiumAI

from src.llm_model import summarize

# Dependencies:
# pip install pytest-mock
import pytest


class TestSummarize:

    # Correctly substitutes transcription text into SUMMARY_PROMPT
    def test_correct_substitution(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Handles empty transcription text gracefully
    def test_empty_transcription(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = ""
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Successfully generates summary using provided model and prompt
    def test_successful_summary_generation(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Returns a coherent summary for standard inputs
    def test_returns_coherent_summary(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Handles typical transcription texts without errors
    def test_handles_typical_transcription_texts(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a typical transcription text."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Uses the correct model for generating summaries
    def test_uses_correct_model(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Manages very large transcription texts without performance issues
    def test_manages_large_texts(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a very large transcription text. It contains a lot of information and details."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Deals with special characters in transcription text
    def test_deals_with_special_characters(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a transcription with special characters: !@#$%^&*()_+"
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Handles missing or invalid model names
    def test_handles_missing_model_name(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "invalid_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_not_called()

    # Manages transcription text with unusual formatting or structure
    def test_manage_unusual_formatting(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Verifies that SUMMARY_PROMPT is correctly formatted before substitution
    def test_correct_formatting_before_substitution(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Ensures generate function is called with correct parameters
    def test_generate_called_with_correct_parameters(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Validates that the output summary maintains the structure outlined in SUMMARY_PROMPT
    def test_output_structure(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")
        summarize(model, text)

        mock_generate.assert_called_once_with(model, expected_prompt)

    # Checks for proper error handling when generate function fails
    def test_generate_function_failure_handling(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mocker.patch(
            "src.llm_model.generate", side_effect=Exception("Generate function failed")
        )

        with pytest.raises(Exception) as exc_info:
            summarize(model, text)

        assert str(exc_info.value) == "Generate function failed"

    # Tests for performance with multiple concurrent summarize calls
    def test_performance_multiple_concurrent_calls(self, mocker):
        from src.llm_model import summarize
        from src.promts import SUMMARY_PROMPT

        model = "test_model"
        text = "This is a test transcription."
        expected_prompt = SUMMARY_PROMPT.substitute({"transcription": text})

        mock_generate = mocker.patch("src.llm_model.generate")

        # Call summarize function multiple times concurrently
        for _ in range(10):
            summarize(model, text)

        # Assert that generate function is called 10 times with the expected prompt
        mock_generate.assert_called(10)
