name: Pylint

on: [push, pull_request]


jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for black
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: check formatting
        run: |
          pip install black
          black --check .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: check formatting
        run: |
          pip install black
          black --check .

      - name: Install dependencies
        run: |
           pip install pylint
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name: code review
        run: pylint *.py src
