name: Pylint

on: [push, pull_request]


jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # TODO: we should not install all requirements here if we can avoid it, we could install only pylint
      - name: Install dependencies
        run: |
           pip install pylint==3.0.3
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt


      - name: code review
        run: pylint *.py src
